### ISSUE TITLE
CreateTable events are not getting processed

### ISSUE THREAD

**Issue by SercanKaraoglu** [aws-samples/lake-formation-permissions-sync#3]
https://github.com/aws-samples/lake-formation-permissions-sync/blob/2f25638ece65ba983523877b1ed11f669b357b53/realtime/glue-lf-replicate-event/lambda_function.py#L91

Indentation error causes following error:

```Received exception local variable 's3_table_target_bucket_name' referenced before assignment```

**Comment by vivshrivastava** [comment]
Resolved.
